schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_name:
          type: string
          description: "This name for your VPC"
          default: proton-demo
        vpc_cidr:
          type: string
          description: "This CIDR range for your VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnets_cidrs:
          type: array
          items:
            type: string
            description: networkIds
            #default : ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
        public_subnets_cidrs:
          type: array
          items:
            type: string
            description: networkIds
            #default : ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]