schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_name:
          type: string
          description: "This name for your VPC"
          default: proton-demo
        vpc_cidr:
          type: string
          description: "This CIDR range for your VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_cidr_1:
          type: string
          description: "The CIDR range for public subnet one"
          default: "10.0.101.0/24"
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_cidr_2:
          type: string
          description: "The CIDR range for public subnet two"
          default:  "10.0.102.0/24"
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_cidr_3:
          type: string
          description: "The CIDR range for public subnet three"
          default: "10.0.103.0/24"
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        private_subnet_cidr_1:
          type: string
          default: "10.0.1.0/24" 
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
          description: "The CIDR range for private subnet one"
        private_subnet_cidr_2:
          type: string
          default: "10.0.2.0/24" 
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
          description: "The CIDR range for private subnet tw0"          
        private_subnet_cidr_3:
          type: string
          default: "10.0.3.0/24" 
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
          description: "The CIDR range for private subnet three"